name: ClimAg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dask
  - rioxarray
  - geopandas
  - intake-esm
  - cartopy
  - aiohttp
  - odfpy
  - cfgrib
  - netcdf4
  - pooch
  - rasterstats
  - cdo  # unavailable on Windows; use Conda with WSL
  - esmpy=8.3.1  # module name change compatibility for xesmf
  - xesmf  # unavailable on Windows; use Conda with WSL
  - cf_xarray  # xesmf dependency
  - sparse  # xesmf dependency
  - numba  # xesmf dependency
  - mpi  # xesmf dependency
  - geocube
  - matplotlib
  - nc-time-axis
  - seaborn
  - pytest
  - flake8
  - pylint
  - black
  - jupyterlab
