name: ClimAg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - dask
  - matplotlib
  - rioxarray
  - geopandas
  - netcdf4
  - bottleneck
  - nc-time-axis
  - py-cordex
  - python-cdo
  - regionmask
  - intake-esm
  - aiohttp
