name: ClimAg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dask
  - matplotlib
  - rioxarray
  - geopandas
  - intake-esm>=2022.9.18
  - cartopy
  - nc-time-axis
  - jupyterlab
  - flake8
  - pylint
  - aiohttp
  - odfpy
  - black
  - seaborn
