name: ClimAg
channels:
  - conda-forge
  - anaconda
dependencies:
  - python
  - jupyterlab
  - planetary-computer
  - xarray
  - fsspec
  - geopandas
  - rich
  - py-cordex
  - intake
  - tqdm
  - dask
  - regionmask
