name: ClimAg
channels:
  - conda-forge
  - anaconda
dependencies:
  - python
  - jupyterlab
  - dask
  # - planetary-computer
  # - xarray
  # - fsspec
  # - geopandas
  # - rich
  # - py-cordex
  # - intake
  # - tqdm
  # - regionmask
